// Generated by js_of_ocaml
//# buildInfo:effects=disabled, kind=cmo, use-js-string=true, version=6.0.1

//# unitInfo: Provides: Dune__exe__Exp
//# unitInfo: Requires: Stdlib, Stdlib__List, Stdlib__String
(function
  (globalThis){
   "use strict";
   var runtime = globalThis.jsoo_runtime, cst$2 = ")";
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) === 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) === 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    cst = cst$2,
    cst$0 = " ",
    cst$1 = cst$2,
    Stdlib = global_data.Stdlib,
    Stdlib_List = global_data.Stdlib__List,
    Stdlib_String = global_data.Stdlib__String,
    cst_Var = "Var(",
    cst_Call = "Call(";
   function to_string(param){
    if(0 === param[0]){
     var s = param[1], _a_ = caml_call2(Stdlib[28], s, cst);
     return caml_call2(Stdlib[28], cst_Var, _a_);
    }
    var
     xs = param[1],
     _b_ = caml_call2(Stdlib_List[20], to_string, xs),
     s$0 = caml_call1(caml_call1(Stdlib_String[7], cst$0), _b_),
     _c_ = caml_call2(Stdlib[28], s$0, cst$1);
    return caml_call2(Stdlib[28], cst_Call, _c_);
   }
   var Dune_exe_Exp = [0, to_string];
   runtime.caml_register_global(8, Dune_exe_Exp, "Dune__exe__Exp");
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLm1haW4uZW9ianMvanNvby9kdW5lX19leGVfX0V4cC5jbW8uanMiLCJzZWN0aW9ucyI6W3sib2Zmc2V0Ijp7ImxpbmUiOjgsImNvbHVtbiI6MH0sIm1hcCI6eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLm1haW4uZW9ianMvanNvby9kdW5lX19leGVfX0V4cC5jbW8uanMiLCJuYW1lcyI6WyJydW50aW1lIiwiY3N0IiwiY2FtbF9jYWxsMSIsImYiLCJhMCIsImNhbWxfY2FsbDIiLCJhMSIsImdsb2JhbF9kYXRhIiwiU3RkbGliIiwiU3RkbGliX0xpc3QiLCJTdGRsaWJfU3RyaW5nIiwiY3N0X1ZhciIsImNzdF9DYWxsIiwidG9fc3RyaW5nIiwicGFyYW0iLCJzIiwieHMiLCJEdW5lX2V4ZV9FeHAiXSwic291cmNlcyI6WyIvYnVpbHRpbi9ibGFja2JveC5tbCIsIi93b3Jrc3BhY2Vfcm9vdC9leHAubWwiXSwibWFwcGluZ3MiOiJPQUFBQSxVQUFBLHlCQUFBQyxRQUFBO0FBQUEsWUFBQUMsV0FBQUMsR0FBQUM7QUFBQUEsSUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBLFlBQUFDLFdBQUFGLEdBQUFDLElBQUFFO0FBQUFBLElBQUE7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBLElBQUFDLGNBQUE7QUFBQSxJQUFBTixNQUFBO0FBQUEsSUFBQUEsUUFBQTtBQUFBLElBQUFBLFFBQUE7QUFBQSxJQUFBTyxTQUFBO0FBQUEsSUFBQUMsY0FBQTtBQUFBLElBQUFDLGdCQUFBO0FBQUEsSUFBQUMsVUFBQTtBQUFBLElBQUFDLFdBQUE7QUFBQSxZQUFBQyxVQUFBQztBQUFBQSxJQ0lvQjtBQUFBLFNBQUFDLElBQUEsZ0JBQ0E7QUFBQSxLQUFPLDJDQUdOO0FBQUE7QUFBQTtBQUFBLEtBQUFDLEtBSkQ7QUFBQSxXQUdSO0FBQUEsS0FBQUQsTUFBQSxXQUF5QjtBQUFBLFdBQ3ZCO0FBQUEsSUFBTztBQUFBO0FBQUEsT0FBQUUsZURSckIiLCJzb3VyY2VzQ29udGVudCI6WyIoKiBnZW5lcmF0ZWQgY29kZSAqKSIsInR5cGUgdCA9XG58IFZhciBvZiBzdHJpbmdcbnwgQ2FsbCBvZiB0IGxpc3RcblxubGV0IHJlYyB0b19zdHJpbmcgPSBmdW5jdGlvblxufCBWYXIgcyAtPiBcIlZhcihcIiBeIHMgXiBcIilcIlxufCBDYWxsIHhzIC0+XG4gICAgbGV0IHMgPSBMaXN0Lm1hcCB0b19zdHJpbmcgeHMgfD4gU3RyaW5nLmNvbmNhdCBcIiBcIiBpblxuICAgIFwiQ2FsbChcIiBeIHMgXiBcIilcIiJdLCJpZ25vcmVMaXN0IjpbMF19fV19
